document.getElementById("string").textContent = "A sting is anything that is surronded by single quotes double quotes or backtips";

//Example
let firstName = "Divine";
console.log(`my name is ${firstName}`);
console.log(typeof firstName);

document.getElementById("number").textContent = "A number is any number that is not surrounded by double quotes etc";

// Example

let date = 2025;
console.log(`${date} is a new year`);
console.log(typeof date);


document.getElementById("boolean").textContent = "A boolean is a true or false value";


// Example
let isStudent = true;
console.log(`I am a student ${isStudent}`)
console.log(isStudent);
console.log(typeof isStudent);

document.getElementById("undefined").textContent = "undefined is a value that is not assigned to  a varible";

// Example

let age;
console.log(`age is ${age}`);
console.log(typeof age);

document.getElementById("null").textContent = "null is a value that is assigned to a variable but the value is empty";

// Example

let car = null;
console.log(`the value of car is ${car}`);
console.log(typeof car);

document.getElementById("symbol").textContent = "A symbol is a unique value that is generated by the symbol() function";

// Example

let syn = Symbol;
console.log(`the value of syn is ${syn}`);
console.log(typeof syn);

document.getElementById("object").textContent = "An object is a collection of keyvalue pairs";

// Example 

let person = {};
person.name = "Divine";
console.log(person);
console.log(typeof person);

document.getElementById("array").textContent = "An array is a collection of values";

// Example

let fruits = ["apple", "orange", "banana"];
console.log(fruits);
console.log(typeof fruits);








